import "bootstrap/dist/css/bootstrap.min.css"; // ✅ Bootstrap CSS

import {
  Geist,
  Geist_Mono,
  Quicksand,
  Domine,
  Raleway,
} from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
// import Footer from "../components/Footer";
import { ToastContainer } from "react-toastify";
import MegaMenu from "../components/Megamenu";
import dynamic from "next/dynamic";

const Footer = dynamic(() => import("../components/Footer"), {
  ssr: true,
  loading: () => <div style={{ height: 200 }}>Loading...</div>,
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // all the weights you want to use
  display: "swap",
  variable: "--font-quicksand", // optional: lets you use a CSS variable
});

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // all the weights you want to use
  display: "swap",
  variable: "--font-raleway", // optional: lets you use a CSS variable
});

const domine = Domine({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // all the weights you want to use
  display: "swap",
  variable: "--font-domine", // optional: lets you use a CSS variable
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${quicksand.variable} ${domine.variable} ${raleway.variable}`}
      >
        <Header />
        <MegaMenu />

        {children}
        <ToastContainer />
        <Footer />
      </body>
    </html>
  );
}
